#
# Copyright (C) 2011 Klokan Technologies GmbH (info@klokantech.com)
#
# The Python code in this page is free software: you can
# redistribute it and/or modify it under the terms of the GNU
# General Public License (GNU GPL) as published by the Free Software
# Foundation, either version 3 of the License, or (at your option)
# any later version.  The code is distributed WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU GPL for more details.
#
# USE OF THIS CODE OR ANY PART OF IT IN A NONFREE SOFTWARE IS NOT ALLOWED
# WITHOUT PRIOR WRITTEN PERMISSION FROM KLOKAN TECHNOLOGIES GMBH.
#
# As additional permission under GNU GPL version 3 section 7, you
# may distribute non-source (e.g., minimized or compacted) forms of
# that code without the copy of the GNU GPL normally required by
# section 4, provided you include this license notice and a URL
# through which recipients can access the Corresponding Source.
#
# @author petr.sloup@klokantech.com (Petr Sloup)
#
# Known issues:
# Does not fully support "inline" /* */ comments
#

import os
import string

output = open('./shaderbank_codes.js', 'w')

output.write("""/*
 * Copyright (C) 2011 Klokan Technologies GmbH (info@klokantech.com)
 *
 * The JavaScript code in this page is free software: you can
 * redistribute it and/or modify it under the terms of the GNU
 * General Public License (GNU GPL) as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version.  The code is distributed WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU GPL for more details.
 *
 * USE OF THIS CODE OR ANY PART OF IT IN A NONFREE SOFTWARE IS NOT ALLOWED
 * WITHOUT PRIOR WRITTEN PERMISSION FROM KLOKAN TECHNOLOGIES GMBH.
 *
 * As additional permission under GNU GPL version 3 section 7, you
 * may distribute non-source (e.g., minimized or compacted) forms of
 * that code without the copy of the GNU GPL normally required by
 * section 4, provided you include this license notice and a URL
 * through which recipients can access the Corresponding Source.
 *
 */

/**
 * @fileoverview This file is automatically generated from all *.glsl files
 * Notes:
 *    All comments are trimmed.
 *    All lines starting with # has to start and end with newline symbol.
 *    All leading and trailing spaces are trimmed.
 *    All redundant whitespace can be reduced to single space. (Not yet implemented)
 */

goog.provide('we.shaderbank.codes');\n""")

shaderDir = './shaders/'

# Following operators serve as token delimiters,
# so we can safely remove any whitespace around them.
# Hopefully I didn't underestimate anything and this won't break anything :)
operators = ['(', ')', '[', ']', '*', '/', '+', '-', '<', '>', '<=', '>=', '==',
             '!=', '&&', '^^', '||', '=', '+=', '-=', '*=', '/=', '{', '}', ';',
             ',']

def isGLSL(x): return x.endswith('.glsl')

files = filter(isGLSL, os.listdir(shaderDir))

for file in files:
  output.write("\n\n/** @type {string} */\nwe.shaderbank.codes['")
  output.write(file)
  output.write("'] = '")

  inComment = False
  newLine = True

  shader = open(shaderDir + file, 'r')
  for line in shader:
    line = string.split(line.strip(), '//', 1)[0].expandtabs(1)

    if len(line) == 0:
      continue

    if (not inComment) and (line.find('/*') != -1):
      inComment = True

    if not inComment:
      if line.startswith('#') and not newLine:
        output.write('\\n')

      for operator in operators:
        line = line.replace(' ' + operator, operator)
        line = line.replace(operator + ' ', operator)

      output.write(line)
      newLine = False

      if line.startswith('#'):
        output.write('\\n')
        newLine = True

    if inComment and (line.find('*/') != -1):
      inComment = False

  output.write("\';\n")

output.close()
